name: Dry generation with 'serializers-generator'

on:
  workflow_dispatch:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches: [main]

jobs:
  dry_generation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone 'message-definitions'
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          submodules: true
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Print go envs
        run:  go env

      - name: Install Python requirements
        run:  'pip install -r serializers-generator/requirements.txt'
      - name: Install 'protoc'
        run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y protobuf-compiler
      - name: Install protoc 'json-schema' extension
        run: |
          go install github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema@latest

      - name: Run C++ files generation
        working-directory: ./serializers-generator
        run: python3 src/generator/main.py ../telemetry /tmp/generated
      - name: Run JSON Schema files generation
        working-directory: ./serializers-generator
        run: |
          ./scripts/generate_schemas /tmp/generated/proto /tmp/generated
